development:
  secret_key_base: 6e79e7fc7f841edce92e24e9f07926ed4aa0b6d495714b9f2c918a899f3c95695007156ac37adb83e74961cd9fe006fec3f976ef147bebd5c80319acb93fa12e
  STRIPE_PUBLISHABLE_KEY: pk_test_ieflQAMrJzl0wykzAgpUYnDb
  STRIPE_SECRET_KEY: sk_test_nIfrUaZ4aL55itb212Ib0sEO
  STRIPE_CONNECT_CLIENT_ID: ca_6fhUrI5kJKzZKUTMo2FmLUT0ZBmDMKz2

test:
  secret_key_base: 1439703151c597e6cc97ca58f3e2aa63082e9f20646eda0a6457c1d391027b4e999f11250981deee8e37dce404a5c6f1534b1bd8cf0eca2a0d1e1507028f0c33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  STRIPE_PUBLISHABLE_KEY: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  STRIPE_SECRET_KEY: <%= ENV["STRIPE_SECRET_KEY"] %>
  STRIPE_CONNECT_CLIENT_ID: ca_6fhU8iCQK7cJqPGzIuuAy7pX627Cz0ZO # TODO: ADD TO HEROKU ENV